services:
  spotify-stats-service:
    container_name: spotify-stats-service
    image: ghcr.io/lockhart07/spotify-stats:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; r=requests.get('http://localhost:9000/ping'); r.raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - backend

networks:
  backend:
    driver: bridge
