services:
  spotify-stats-service:
    container_name: spotify-stats-service
    image: ghcr.io/lockhart07/spotify-stats:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s=socket.socket(); s.settimeout(5); s.connect(('localhost', 8000)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
